### ISSUE TITLE
Server should listen on localhost by default

### ISSUE THREAD

**Issue by retpoline** [rakibtg/docker-web-gui#24]
When you start the app, it says goto http://localhost:3230 to use it, which may lead users to believe it's listening on the localhost interface, but by default it's actually listening on the network interface. Without authentication, it's probably better that it listens on the local interface by default instead with the user having the ability to configure it to listen on the network.

Not a bug per-sa, but just a security hardening and UI suggestion.

**Comment by rakibtg** [comment]
@retpoline  Hi! This has been fixed along with the permission issues. Please pull latest changes from `master`. Then use `docker-compose build` and `docker-compose up` to run the application.

If you are still facing this issue please re-open it.
