### ISSUE TITLE
Non-MacOS support for containers

### ISSUE THREAD

**Issue by kennethbruskiewicz** [rakibtg/docker-web-gui#61]
Is there a reason this can't be expanded to support other operating systems?

**Comment by rakibtg** [comment]
@kennethbruskiewicz I just pushed some changes to better support for windows. Pull latest from `master` and try to use it using docker composer.

```shell
docker-compose build
docker-compose up
```

![image](https://github.com/rakibtg/docker-web-gui/assets/5412730/1f90a4a3-6d17-4293-8e6b-c2890aa0a912)



Make sure to use wsl2, just a tips for windows users.
